[program:haitaka_corrected_runs]
command=/opt/supervisor-scripts/haitaka-corrected-runs.sh
autostart=false
autorestart=false
startsecs=1
stopsignal=INT
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/stdout
redirect_stderr=true
stdout_logfile_maxbytes=0
