[program:haitaka_corrected_disk_monitor]
command=/opt/supervisor-scripts/haitaka-corrected-disk-monitor.sh
autostart=false
autorestart=false
startsecs=1
stopsignal=TERM
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/stdout
redirect_stderr=true
stdout_logfile_maxbytes=0
