[package]
name = "haitaka_wasm"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
haitaka = { path = "../haitaka", default-features = false }
wasm-bindgen = "0.2.100"
js-sys = "0.3.90"
instant = { version = "0.1", features = ["wasm-bindgen"] }

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
criterion = { version = "0.3.5", features = ["html_reports"] }
rand = "0.9"

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test = "=0.3.68"

[[bench]]
name = "nnue"
harness = false

[features]
annan = ["haitaka/annan"]
anhoku = ["haitaka/anhoku"]
antouzai = ["haitaka/antouzai"]
taimen = ["haitaka/taimen"]
haimen = ["haitaka/haimen"]
neko = ["haitaka/neko"]
nekoneko = ["haitaka/nekoneko"]
yokoneko = ["haitaka/yokoneko"]
yokonekoneko = ["haitaka/yokonekoneko"]
tenkyo = ["haitaka/tenkyo"]
tenjiku = ["haitaka/tenjiku"]
anki = ["haitaka/anki"]
